// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuantumZhou.Identity.Database;

#nullable disable

namespace QuantumZhou.Identity.Database.Migrations.MySql.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260805151923_EnableAppScopedLdapLogin")]
    partial class EnableAppScopedLdapLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_bin")
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("last_login_ip");

                    b.Property<string>("LastLoginMethod")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_login_method");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nickname");

                    b.Property<string>("NicknameNormalized")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nickname_normalized");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark");

                    b.Property<string>("RemarkNormalized")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark_normalized");

                    b.Property<int>("TotalLoginCount")
                        .HasColumnType("int")
                        .HasColumnName("total_login_count");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.AppLdapAccessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AppRegistrationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("app_registration_id");

                    b.Property<int>("ApprovalSource")
                        .HasColumnType("int")
                        .HasColumnName("approval_source");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LdapCredentialId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ldap_credential_id");

                    b.HasKey("Id");

                    b.HasIndex("LdapCredentialId");

                    b.HasIndex("AppRegistrationId", "LdapCredentialId")
                        .IsUnique();

                    b.ToTable("app_ldap_accesses", (string)null);
                });

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.AppRegistrationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("app_id");

                    b.Property<string>("AppIdNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("app_id_normalized");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("app_name");

                    b.Property<string>("AppSecretHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("app_secret_hash");

                    b.Property<DateTime?>("CallbackExpiresAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("callback_expires_at");

                    b.Property<string>("CallbackUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("callback_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("LdapLoginMode")
                        .HasColumnType("int")
                        .HasColumnName("ldap_login_mode");

                    b.HasKey("Id");

                    b.HasIndex("AppIdNormalized")
                        .IsUnique();

                    b.ToTable("app_registrations", (string)null);
                });

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("actor_name");

                    b.Property<string>("AfterSnapshot")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("after_snapshot");

                    b.Property<string>("BeforeSnapshot")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("before_snapshot");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("client_ip");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Action", "CreatedAt");

                    b.HasIndex("ActorId", "CreatedAt");

                    b.HasIndex("TargetType", "TargetId", "CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.LdapCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DirectoryKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("directory_key");

                    b.Property<string>("DirectoryKeyNormalized")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("directory_key_normalized");

                    b.Property<Guid>("ObjectGuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("object_guid");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sam_account_name");

                    b.Property<string>("SamAccountNameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sam_account_name_normalized");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_principal_name");

                    b.Property<string>("UserPrincipalNameNormalized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_principal_name_normalized");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DirectoryKeyNormalized", "ObjectGuid")
                        .IsUnique();

                    b.HasIndex("DirectoryKeyNormalized", "SamAccountNameNormalized")
                        .IsUnique();

                    b.HasIndex("DirectoryKeyNormalized", "UserPrincipalNameNormalized")
                        .IsUnique();

                    b.ToTable("ldap_credentials", (string)null);
                });

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.LoginAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_attempts");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_attempt_at");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockout_until");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username_normalized");

                    b.HasKey("Id");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("login_attempts", (string)null);
                });

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.LoginHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("AppId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("app_id");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("auth_method");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("client_ip");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("user_agent");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ClientIp");

                    b.HasIndex("CreatedAt");

                    b.ToTable("login_histories", (string)null);
                });

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.OtpEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LockoutUntil")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockout_until");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("otps", (string)null);
                });

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.PasswordCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username_normalized");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("password_credentials", (string)null);
                });

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_revoked");

                    b.Property<Guid?>("LdapCredentialId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ldap_credential_id");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("token_value");

                    b.HasKey("Id");

                    b.HasIndex("LdapCredentialId");

                    b.HasIndex("TokenValue")
                        .IsUnique();

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_refresh_tokens_app_id_not_empty", "app_id <> ''");
                        });
                });

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.SecurityKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedPrivateKeyParams")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("encrypted_private_key_params");

                    b.Property<string>("EncryptionSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("encryption_salt");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("key_id");

                    b.Property<string>("PublicKeyExponent")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("public_key_exponent");

                    b.Property<string>("PublicKeyModulus")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("public_key_modulus");

                    b.HasKey("Id");

                    b.HasIndex("KeyId")
                        .IsUnique();

                    b.ToTable("security_keys", (string)null);
                });

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.UserLoginEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderNameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("provider_name_normalized");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("provider_user_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ProviderNameNormalized", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.AppLdapAccessEntity", b =>
                {
                    b.HasOne("QuantumZhou.Identity.Database.Entity.AppRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("AppRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuantumZhou.Identity.Database.Entity.LdapCredentialEntity", null)
                        .WithMany()
                        .HasForeignKey("LdapCredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuantumZhou.Identity.Database.Entity.LdapCredentialEntity", b =>
                {
                    b.HasOne("QuantumZhou.Identity.Database.Entity.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
