<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.62.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contract\QuantumZhou.Identity.Contract.csproj" />
    <ProjectReference Include="..\Database\QuantumZhou.Identity.Database.csproj" />
    <ProjectReference Include="..\Domain\QuantumZhou.Identity.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
