// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignaCore.ReferenceBff.Database;

#nullable disable

namespace SignaCore.ReferenceBff.Database.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(ReferenceBffDbContext))]
    [Migration("20260920152702_AddSharedInstallationAndAudit")]
    partial class AddSharedInstallationAndAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ServiceMantle.Persistence.EntityFrameworkCore.ManagementAuditLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_ip");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("OperatorDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_display_name");

                    b.Property<string>("OperatorId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_id");

                    b.Property<string>("OperatorSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_source");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER")
                        .HasColumnName("outcome");

                    b.Property<string>("SecurityDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("security_description");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_occurred_at_utc_id");

                    b.HasIndex("Action", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_action_occurred_at_utc_id");

                    b.HasIndex("OperatorId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_operator_id_occurred_at_utc_id");

                    b.HasIndex("TargetId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_target_id_occurred_at_utc_id");

                    b.HasIndex("TargetType", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_target_type_occurred_at_utc_id");

                    b.HasIndex("TargetType", "TargetId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_target_occurred_at_utc_id");

                    b.ToTable("service_audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_audit_logs_action_length", "action IS NULL OR octet_length(action) <= 800");

                            t.HasCheckConstraint("ck_service_audit_logs_client_ip_length", "client_ip IS NULL OR octet_length(client_ip) <= 256");

                            t.HasCheckConstraint("ck_service_audit_logs_correlation_id_length", "correlation_id IS NULL OR octet_length(correlation_id) <= 512");

                            t.HasCheckConstraint("ck_service_audit_logs_id_length", "id IS NULL OR octet_length(id) <= 144");

                            t.HasCheckConstraint("ck_service_audit_logs_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_service_audit_logs_metadata_json_length", "metadata_json IS NULL OR octet_length(metadata_json) <= 262144");

                            t.HasCheckConstraint("ck_service_audit_logs_operator_display_name_length", "operator_display_name IS NULL OR octet_length(operator_display_name) <= 1024");

                            t.HasCheckConstraint("ck_service_audit_logs_operator_id_length", "operator_id IS NULL OR octet_length(operator_id) <= 1024");

                            t.HasCheckConstraint("ck_service_audit_logs_operator_source_length", "operator_source IS NULL OR octet_length(operator_source) <= 400");

                            t.HasCheckConstraint("ck_service_audit_logs_security_description_length", "security_description IS NULL OR octet_length(security_description) <= 16000");

                            t.HasCheckConstraint("ck_service_audit_logs_target_id_length", "target_id IS NULL OR octet_length(target_id) <= 1024");

                            t.HasCheckConstraint("ck_service_audit_logs_target_type_length", "target_type IS NULL OR octet_length(target_type) <= 800");
                        });
                });

            modelBuilder.Entity("ServiceMantle.Persistence.EntityFrameworkCore.ServiceInstallationEntity", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("service_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("SetupCodeDigest")
                        .HasMaxLength(74)
                        .HasColumnType("TEXT")
                        .HasColumnName("setup_code_digest");

                    b.Property<DateTime?>("SetupCodeExpiresAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("setup_code_expires_at_utc");

                    b.Property<int>("SetupCodeGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("setup_code_generation");

                    b.Property<DateTime?>("SetupCodeIssuedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("setup_code_issued_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("ServiceId");

                    b.ToTable("service_installations", (string)null);
                });

            modelBuilder.Entity("SignaCore.ReferenceBff.Database.ManagementRoleBindingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("issuer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("PK_management_role_bindings");

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasDatabaseName("IX_management_role_bindings_role");

                    b.ToTable("management_role_bindings", null, t =>
                        {
                            t.HasCheckConstraint("CK_management_role_bindings_role_fixed", "role = 'system-administrator'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
