// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignaCore.ReferenceBff.Database;

#nullable disable

namespace SignaCore.ReferenceBff.Database.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(ReferenceBffDbContext))]
    [Migration("20260920023218_AddManagementRoleBindings")]
    partial class AddManagementRoleBindings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SignaCore.ReferenceBff.Database.ManagementRoleBindingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("issuer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("PK_management_role_bindings");

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasDatabaseName("IX_management_role_bindings_role");

                    b.ToTable("management_role_bindings", null, t =>
                        {
                            t.HasCheckConstraint("CK_management_role_bindings_role_fixed", "role = 'system-administrator'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
