// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SignaCore.Database;

#nullable disable

namespace SignaCore.Database.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260925033310_AddOidcRateLimitBuckets")]
    partial class AddOidcRateLimitBuckets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceMantle.Persistence.EntityFrameworkCore.DataProtectionKeyEntity", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("service_id");

                    b.Property<string>("KeyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_id");

                    b.Property<string>("EncryptedXml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_xml");

                    b.HasKey("ServiceId", "KeyId");

                    b.ToTable("service_data_protection_keys", (string)null);
                });

            modelBuilder.Entity("ServiceMantle.Persistence.EntityFrameworkCore.ManagementAuditLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_ip");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(262144)
                        .HasColumnType("character varying(262144)")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("OperatorDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operator_display_name");

                    b.Property<string>("OperatorId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operator_id");

                    b.Property<string>("OperatorSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operator_source");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<string>("SecurityDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("security_description");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_occurred_at_utc_id");

                    b.HasIndex("Action", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_action_occurred_at_utc_id");

                    b.HasIndex("OperatorId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_operator_id_occurred_at_utc_id");

                    b.HasIndex("TargetId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_target_id_occurred_at_utc_id");

                    b.HasIndex("TargetType", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_target_type_occurred_at_utc_id");

                    b.HasIndex("TargetType", "TargetId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_target_occurred_at_utc_id");

                    b.ToTable("service_audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_audit_logs_action_length", "action IS NULL OR octet_length(action) <= 800");

                            t.HasCheckConstraint("ck_service_audit_logs_client_ip_length", "client_ip IS NULL OR octet_length(client_ip) <= 256");

                            t.HasCheckConstraint("ck_service_audit_logs_correlation_id_length", "correlation_id IS NULL OR octet_length(correlation_id) <= 512");

                            t.HasCheckConstraint("ck_service_audit_logs_id_length", "id IS NULL OR octet_length(id) <= 144");

                            t.HasCheckConstraint("ck_service_audit_logs_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_service_audit_logs_metadata_json_length", "metadata_json IS NULL OR octet_length(metadata_json) <= 262144");

                            t.HasCheckConstraint("ck_service_audit_logs_operator_display_name_length", "operator_display_name IS NULL OR octet_length(operator_display_name) <= 1024");

                            t.HasCheckConstraint("ck_service_audit_logs_operator_id_length", "operator_id IS NULL OR octet_length(operator_id) <= 1024");

                            t.HasCheckConstraint("ck_service_audit_logs_operator_source_length", "operator_source IS NULL OR octet_length(operator_source) <= 400");

                            t.HasCheckConstraint("ck_service_audit_logs_security_description_length", "security_description IS NULL OR octet_length(security_description) <= 16000");

                            t.HasCheckConstraint("ck_service_audit_logs_target_id_length", "target_id IS NULL OR octet_length(target_id) <= 1024");

                            t.HasCheckConstraint("ck_service_audit_logs_target_type_length", "target_type IS NULL OR octet_length(target_type) <= 800");
                        });
                });

            modelBuilder.Entity("ServiceMantle.Persistence.EntityFrameworkCore.ServiceInstallationEntity", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("service_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("SetupCodeDigest")
                        .HasMaxLength(74)
                        .HasColumnType("character varying(74)")
                        .HasColumnName("setup_code_digest");

                    b.Property<DateTime?>("SetupCodeExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("setup_code_expires_at_utc");

                    b.Property<int>("SetupCodeGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("setup_code_generation");

                    b.Property<DateTime?>("SetupCodeIssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("setup_code_issued_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("ServiceId");

                    b.ToTable("service_installations", (string)null);
                });

            modelBuilder.Entity("ServiceMantle.Persistence.EntityFrameworkCore.ServiceSettingEntity", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("service_id");

                    b.Property<bool>("RestartRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("restart_required");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("values_json");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("ServiceId");

                    b.ToTable("service_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_settings_version", "version > 0");
                        });
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(64)
                        .HasColumnType("text")
                        .HasColumnName("last_login_ip");

                    b.Property<string>("LastLoginMethod")
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("last_login_method");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("NicknameNormalized")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname_normalized");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("RemarkNormalized")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark_normalized");

                    b.Property<int>("TotalLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_login_count");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AppExchangeTrustEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_registration_id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SourceAppRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_app_registration_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceAppRegistrationId");

                    b.HasIndex("AppRegistrationId", "SourceAppRegistrationId")
                        .IsUnique();

                    b.ToTable("app_exchange_trusts", null, t =>
                        {
                            t.HasCheckConstraint("CK_app_exchange_trusts_no_self_trust", "app_registration_id <> source_app_registration_id");
                        });
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AppLdapAccessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_registration_id");

                    b.Property<int>("ApprovalSource")
                        .HasColumnType("integer")
                        .HasColumnName("approval_source");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LdapCredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("ldap_credential_id");

                    b.HasKey("Id");

                    b.HasIndex("LdapCredentialId");

                    b.HasIndex("AppRegistrationId", "LdapCredentialId")
                        .IsUnique();

                    b.ToTable("app_ldap_accesses", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AppRedirectUriEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_registration_id");

                    b.Property<string>("CanonicalUri")
                        .IsRequired()
                        .HasMaxLength(501)
                        .HasColumnType("character varying(501)")
                        .HasColumnName("canonical_uri");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.HasKey("Id");

                    b.HasIndex("AppRegistrationId", "Kind", "CanonicalUri")
                        .IsUnique();

                    b.ToTable("app_redirect_uris", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AppRegistrationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowAuthorizationCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_authorization_code");

                    b.Property<bool>("AllowRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_refresh_token");

                    b.Property<string>("AllowedScopes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("openid")
                        .HasColumnName("allowed_scopes");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("app_id");

                    b.Property<string>("AppIdNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("app_id_normalized");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("app_name");

                    b.Property<string>("AppSecretHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("app_secret_hash");

                    b.Property<int>("AudienceMode")
                        .HasColumnType("integer")
                        .HasColumnName("audience_mode");

                    b.Property<DateTimeOffset?>("CallbackExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("callback_expires_at");

                    b.Property<string>("CallbackUrl")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("callback_url");

                    b.Property<int>("ClientType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("client_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int?>("IdentitySessionMaxAgeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("identity_session_max_age_seconds");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LdapLoginMode")
                        .HasColumnType("integer")
                        .HasColumnName("ldap_login_mode");

                    b.Property<int>("SmsLoginMode")
                        .HasColumnType("integer")
                        .HasColumnName("sms_login_mode");

                    b.Property<string>("SmsProfileKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sms_profile_key");

                    b.Property<int>("WechatLoginMode")
                        .HasColumnType("integer")
                        .HasColumnName("wechat_login_mode");

                    b.HasKey("Id");

                    b.HasIndex("AppIdNormalized")
                        .IsUnique();

                    b.ToTable("app_registrations", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AppSmsAccessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_registration_id");

                    b.Property<int>("ApprovalSource")
                        .HasColumnType("integer")
                        .HasColumnName("approval_source");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("UserLoginId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_login_id");

                    b.HasKey("Id");

                    b.HasIndex("UserLoginId");

                    b.HasIndex("AppRegistrationId", "UserLoginId")
                        .IsUnique();

                    b.ToTable("app_sms_accesses", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AppWechatAccessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_registration_id");

                    b.Property<int>("ApprovalSource")
                        .HasColumnType("integer")
                        .HasColumnName("approval_source");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("UserLoginId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_login_id");

                    b.HasKey("Id");

                    b.HasIndex("UserLoginId");

                    b.HasIndex("AppRegistrationId", "UserLoginId")
                        .IsUnique();

                    b.ToTable("app_wechat_accesses", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AuthorizationCodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("AppRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_registration_id");

                    b.Property<DateTimeOffset>("AuthTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("auth_time");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("character varying(43)")
                        .HasColumnName("code_challenge");

                    b.Property<string>("CodeDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)")
                        .HasColumnName("code_digest");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdentitySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_session_id");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nonce");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(501)
                        .HasColumnType("character varying(501)")
                        .HasColumnName("redirect_uri");

                    b.Property<Guid?>("RefreshFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_family_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AppRegistrationId");

                    b.HasIndex("CodeDigest")
                        .IsUnique();

                    b.HasIndex("IdentitySessionId");

                    b.HasIndex("RefreshFamilyId");

                    b.ToTable("authorization_codes", null, t =>
                        {
                            t.HasCheckConstraint("CK_authorization_codes_family_requires_consumption", "refresh_family_id IS NULL OR consumed_at IS NOT NULL");
                        });
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AuthorizationRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_registration_id");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("character varying(43)")
                        .HasColumnName("code_challenge");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("HandleDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)")
                        .HasColumnName("handle_digest");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nonce");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(501)
                        .HasColumnType("character varying(501)")
                        .HasColumnName("redirect_uri");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("AppRegistrationId");

                    b.HasIndex("HandleDigest")
                        .IsUnique();

                    b.ToTable("authorization_requests", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.IdentitySessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("absolute_expires_at");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("auth_method");

                    b.Property<DateTimeOffset>("AuthTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("auth_time");

                    b.Property<DateTimeOffset>("IdleExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("idle_expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("PasswordCredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("password_credential_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PasswordCredentialId");

                    b.ToTable("identity_sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_identity_sessions_revocation_pair", "(revoked_at IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SignaCore.Database.Entity.LdapCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DirectoryKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("directory_key");

                    b.Property<string>("DirectoryKeyNormalized")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("directory_key_normalized");

                    b.Property<Guid>("ObjectGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("object_guid");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sam_account_name");

                    b.Property<string>("SamAccountNameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sam_account_name_normalized");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_principal_name");

                    b.Property<string>("UserPrincipalNameNormalized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_principal_name_normalized");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DirectoryKeyNormalized", "ObjectGuid")
                        .IsUnique();

                    b.HasIndex("DirectoryKeyNormalized", "SamAccountNameNormalized")
                        .IsUnique();

                    b.HasIndex("DirectoryKeyNormalized", "UserPrincipalNameNormalized")
                        .IsUnique();

                    b.ToTable("ldap_credentials", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.LoginAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<DateTimeOffset>("LastAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_attempt_at");

                    b.Property<DateTimeOffset?>("LockoutUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lockout_until");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username_normalized");

                    b.HasKey("Id");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("login_attempts", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.LoginHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AppId")
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("app_id");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("auth_method");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("text")
                        .HasColumnName("client_ip");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ClientIp");

                    b.HasIndex("CreatedAt");

                    b.ToTable("login_histories", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.LogoutRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("AppRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_registration_id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("HandleDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)")
                        .HasColumnName("handle_digest");

                    b.Property<Guid>("IdentitySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_session_id");

                    b.Property<string>("PostLogoutRedirectUri")
                        .HasMaxLength(501)
                        .HasColumnType("character varying(501)")
                        .HasColumnName("post_logout_redirect_uri");

                    b.Property<string>("State")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("AppRegistrationId");

                    b.HasIndex("HandleDigest")
                        .IsUnique();

                    b.ToTable("logout_requests", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.OidcRateLimitBucketEntity", b =>
                {
                    b.Property<string>("Policy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("policy");

                    b.Property<string>("PartitionDigest")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("partition_digest");

                    b.Property<int>("PermitCount")
                        .HasColumnType("integer")
                        .HasColumnName("permit_count");

                    b.Property<DateTimeOffset>("WindowExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("window_expires_at");

                    b.HasKey("Policy", "PartitionDigest");

                    b.HasIndex("WindowExpiresAt");

                    b.ToTable("oidc_rate_limit_buckets", null, t =>
                        {
                            t.HasCheckConstraint("CK_oidc_rate_limit_buckets_digest_length", "length(partition_digest) = 64");

                            t.HasCheckConstraint("CK_oidc_rate_limit_buckets_permit_count", "permit_count BETWEEN 1 AND 90");

                            t.HasCheckConstraint("CK_oidc_rate_limit_buckets_policy", "policy IN ('oidc-authorize', 'oidc-login', 'oidc-token', 'oidc-userinfo', 'oidc-logout', 'oidc-revoke')");
                        });
                });

            modelBuilder.Entity("SignaCore.Database.Entity.OtpEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_registration_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CodeMac")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_mac");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("DaySendCount")
                        .HasColumnType("integer")
                        .HasColumnName("day_send_count");

                    b.Property<DateTimeOffset>("DayWindowStartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("day_window_started_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<int>("HourSendCount")
                        .HasColumnType("integer")
                        .HasColumnName("hour_send_count");

                    b.Property<DateTimeOffset>("HourWindowStartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("hour_window_started_at");

                    b.Property<DateTimeOffset>("LockoutUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lockout_until");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ProfileKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("profile_key");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AppRegistrationId", "Phone")
                        .IsUnique();

                    b.ToTable("otps", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.PasswordCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username_normalized");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("password_credentials", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset?>("AuthTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("auth_time");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("IdentitySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_session_id");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<Guid?>("LdapCredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("ldap_credential_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Scope")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope");

                    b.Property<Guid?>("SmsUserLoginId")
                        .HasColumnType("uuid")
                        .HasColumnName("sms_user_login_id");

                    b.Property<string>("SourceAppId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_app_id");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("token_value");

                    b.Property<Guid?>("WechatUserLoginId")
                        .HasColumnType("uuid")
                        .HasColumnName("wechat_user_login_id");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("IdentitySessionId");

                    b.HasIndex("LdapCredentialId");

                    b.HasIndex("ParentId")
                        .IsUnique();

                    b.HasIndex("SmsUserLoginId");

                    b.HasIndex("TokenValue")
                        .IsUnique();

                    b.HasIndex("WechatUserLoginId");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_refresh_tokens_app_id_not_empty", "app_id <> ''");

                            t.HasCheckConstraint("CK_refresh_tokens_family_marker", "(identity_session_id IS NULL AND scope IS NULL AND auth_time IS NULL AND consumed_at IS NULL AND parent_id IS NULL) OR (identity_session_id IS NOT NULL AND scope IS NOT NULL AND auth_time IS NOT NULL)");

                            t.HasCheckConstraint("CK_refresh_tokens_family_shape", "(family_id = id AND parent_id IS NULL) OR (family_id <> id AND parent_id IS NOT NULL AND parent_id <> id)");
                        });
                });

            modelBuilder.Entity("SignaCore.Database.Entity.SecurityKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedPrivateKeyParams")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("text")
                        .HasColumnName("encrypted_private_key_params");

                    b.Property<string>("EncryptionSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("encryption_salt");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("key_id");

                    b.Property<string>("PublicKeyExponent")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("text")
                        .HasColumnName("public_key_exponent");

                    b.Property<string>("PublicKeyModulus")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("text")
                        .HasColumnName("public_key_modulus");

                    b.HasKey("Id");

                    b.HasIndex("KeyId")
                        .IsUnique();

                    b.ToTable("security_keys", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.UserLoginEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderNameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name_normalized");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("provider_user_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ProviderNameNormalized", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AppExchangeTrustEntity", b =>
                {
                    b.HasOne("SignaCore.Database.Entity.AppRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("AppRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignaCore.Database.Entity.AppRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceAppRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AppLdapAccessEntity", b =>
                {
                    b.HasOne("SignaCore.Database.Entity.AppRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("AppRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignaCore.Database.Entity.LdapCredentialEntity", null)
                        .WithMany()
                        .HasForeignKey("LdapCredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AppRedirectUriEntity", b =>
                {
                    b.HasOne("SignaCore.Database.Entity.AppRegistrationEntity", "AppRegistration")
                        .WithMany("RedirectUris")
                        .HasForeignKey("AppRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRegistration");
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AppSmsAccessEntity", b =>
                {
                    b.HasOne("SignaCore.Database.Entity.AppRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("AppRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignaCore.Database.Entity.UserLoginEntity", null)
                        .WithMany()
                        .HasForeignKey("UserLoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AppWechatAccessEntity", b =>
                {
                    b.HasOne("SignaCore.Database.Entity.AppRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("AppRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignaCore.Database.Entity.UserLoginEntity", null)
                        .WithMany()
                        .HasForeignKey("UserLoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AuthorizationCodeEntity", b =>
                {
                    b.HasOne("SignaCore.Database.Entity.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SignaCore.Database.Entity.AppRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("AppRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SignaCore.Database.Entity.IdentitySessionEntity", null)
                        .WithMany()
                        .HasForeignKey("IdentitySessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SignaCore.Database.Entity.RefreshTokenEntity", null)
                        .WithMany()
                        .HasForeignKey("RefreshFamilyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AuthorizationRequestEntity", b =>
                {
                    b.HasOne("SignaCore.Database.Entity.AppRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("AppRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SignaCore.Database.Entity.IdentitySessionEntity", b =>
                {
                    b.HasOne("SignaCore.Database.Entity.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SignaCore.Database.Entity.PasswordCredentialEntity", null)
                        .WithMany()
                        .HasForeignKey("PasswordCredentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SignaCore.Database.Entity.LdapCredentialEntity", b =>
                {
                    b.HasOne("SignaCore.Database.Entity.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SignaCore.Database.Entity.LogoutRequestEntity", b =>
                {
                    b.HasOne("SignaCore.Database.Entity.AppRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("AppRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SignaCore.Database.Entity.OtpEntity", b =>
                {
                    b.HasOne("SignaCore.Database.Entity.AppRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("AppRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SignaCore.Database.Entity.RefreshTokenEntity", b =>
                {
                    b.HasOne("SignaCore.Database.Entity.RefreshTokenEntity", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SignaCore.Database.Entity.IdentitySessionEntity", null)
                        .WithMany()
                        .HasForeignKey("IdentitySessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SignaCore.Database.Entity.RefreshTokenEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SignaCore.Database.Entity.AppRegistrationEntity", b =>
                {
                    b.Navigation("RedirectUris");
                });
#pragma warning restore 612, 618
        }
    }
}
