<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <InternalsVisibleTo Include="SignaCore.Tests" />
    <InternalsVisibleTo Include="SignaCore.IntegrationTests" />
    <InternalsVisibleTo Include="SignaCore.ReferenceBff.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="ServiceMantle" />
    <PackageReference Include="ServiceMantle.AspNetCore" />
    <PackageReference Include="ServiceMantle.Consul" />
    <PackageReference Include="ServiceMantle.Database.PostgreSql" />
    <PackageReference Include="ServiceMantle.Database.Sqlite" />
    <PackageReference Include="ServiceMantle.Persistence.EntityFrameworkCore" />
    <PackageReference Include="ServiceMantle.Serilog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SignaCore.Database\SignaCore.Database.csproj" />
    <ProjectReference Include="..\SignaCore.Database.Migrations.Sqlite\SignaCore.Database.Migrations.Sqlite.csproj" />
    <ProjectReference Include="..\SignaCore.Domain\SignaCore.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Development.example.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>
